# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build 
  jobs:
  - job: FirstJob 
    steps:
    - bash: echo Build first job 
  - job: secondJob 
    steps:
    - bash: echo Build second job 
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevDeployJob 
    steps:
    - bash: echo DevDeploy Job 
- stage: QADeply
  dependsOn: Build

  jobs:
  - job: QADeployJob 
    steps:
    - bash: echo QADeploy Job 
- stage: ProdDeply
  dependsOn:
  - QADeply
  - DevDeploy
  jobs:
  - job: ProdDeployJob 
    steps:
    - bash: echo ProdDeploy Job 


